# Generated by Django 3.2.4 on 2021-06-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyc_name', models.CharField(max_length=200, verbose_name='Название')),
                ('begin', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Окончание')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=200, verbose_name='Кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='FormOfEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_education', models.CharField(max_length=200, verbose_name='Форма получения образования')),
            ],
        ),
        migrations.CreateModel(
            name='FormsOfTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forms_of_training', models.CharField(max_length=200, verbose_name='Форма обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_cycles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cycles')),
                ('group_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formofeducation')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=200, verbose_name='Ко-во часов')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_form', models.CharField(max_length=200, verbose_name='Форма оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='SourcesOfFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources_of_funding', models.CharField(max_length=200, verbose_name='Источник финансирования')),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialtyByCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_by_cycle', models.CharField(max_length=200, verbose_name='Специальность по циклу')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='Статус цикла')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчество')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('ur_email', models.EmailField(max_length=200, verbose_name='Эл. почта')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('BDay', models.DateTimeField(verbose_name='День рождения')),
                ('ur_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genders')),
                ('ur_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_surname', models.CharField(max_length=200, verbose_name='Фамилия в дипломе')),
                ('diploma_series', models.CharField(max_length=200, verbose_name='Серия диплома')),
                ('diploma_number', models.CharField(max_length=200, verbose_name='Номер диплома')),
                ('identity_series', models.CharField(max_length=200, verbose_name='Серия удостоверение')),
                ('identity_number', models.CharField(max_length=200, verbose_name='Номер удостоверение')),
                ('place_of_work', models.CharField(max_length=200, verbose_name='Место работы (нас. пункт)')),
                ('job', models.CharField(max_length=200, verbose_name='Работа (организация)')),
                ('snils', models.CharField(max_length=200, verbose_name='СНИЛС')),
                ('citizenship', models.CharField(max_length=200, verbose_name='Гражданство (код страны)')),
                ('payment_status', models.CharField(max_length=200, verbose_name='Состояние оплаты')),
                ('disability', models.CharField(max_length=200, verbose_name='Инвалидность')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groups')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
                ('student_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.positions')),
                ('student_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specializations')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='group_funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sourcesoffunding'),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paymentform'),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formsoftraining'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='cyc_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculty'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='cyc_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hours'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='cyc_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialtybycycle'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='cyc_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
